### ISSUE TITLE
ld4 on (v0 - v3)

### ISSUE THREAD

**Issue by zlateski** [fujitsu/xbyak_aarch64#19]
`ld4((v0 - v3), ptr(x0)); <--- (1)` doesn't compile.

Error:   error: no match for ‘operator-’ (operand types are ‘const Xbyak::VReg’ and ‘const Xbyak::VReg’)
         ld4((v0 - v3), ptr(x0));

**Comment by kawakami-k** [comment]
Thank you for your comment.
README.md may be incorrect.
The below may be correct.
```
ld4((v0.b - v3.b), ptr(x0));
```
I'll check and fix it.

**Comment by zlateski** [comment]
As I understand (and correct me if I'm wrong) The users manual - http://docs-api-peg.northeurope.cloudapp.azure.com/assets/dui0801/h/DUI0801H_armasm_user_guide.pdf does require the type specified as one of (8B, 16B, 4H, 8H, 2S, 4S or 2D). So having `ld((v0.b - v3.b), ptr(x0));` can be considered a syntactic sugar.  Why not include `ld4((v0 - v3), ptr(x0));` as well (as described in the README.

**Comment by kawakami-k** [comment]
Sorry, `ld4((v0.b - v3.b), ptr(x0));` is typo. `ld4((v0.b16 - v3.b16), ptr(x0));` and `ld4((v0.b8 - v3.b8), ptr(x0));` are correct.
Syntax of Xbyak_aarch64 is defined to be as close as possible to that of assembler. Currently, Arm assembler only allows
`LD4 { <Vt>.<T>, <Vt2>.<T>, <Vt3>.<T>, <Vt4>.<T> }, [<Xn|SP>]`, where T = (8B, 16B, 4H, 8H, 2S, 4S or 2D). So does Xbyak_aarch64.

`ld4((v0 - v3), ptr(x0));` is reserved for future AArch64 instruction set extension. It may define new behavior for `LD4 { <Vt>, <Vt2>, <Vt3>, <Vt4> }, [<Xn|SP>]`.

**Comment by zlateski** [comment]
Ok, I'm happy with that argument.

I guess it's just the README that has to be changed.
