### ISSUE TITLE
How to use mnemonics to express "prfm pldl1keep, [x1,  #256]".

### ISSUE THREAD

**Issue by AnonymousYWL** [fujitsu/xbyak_aarch64#32]

**Comment by kawakami-k** [comment]
Although the default branch of xbyak_aarch64 is set to the fjmaster, please use the main branch.
We plan to use the main branch as main stream.

Please try the following for "prfm pldl1keep, [x1, #256]".
```
prfm(PLDL1KEEP, ptr( x7, 256 ) );
```

There are some samples of the mnemonic usage in xbyak_aarch64/sample/mnemonic_syntac/*.cpp 
Thank you for your interest in Xbyak_aarch64.

**Comment by lingweiyang** [comment]
Is there no overhead in using JIT to generate code? Why can it improve the performance of deep learning training?

**Comment by kawakami-k** [comment]
It takes less than a second to generate the code. The overhead of code generation is negligible, as deep learning takes a order of hours to days.

**Comment by lingweiyang** [comment]
Thank you for your answer. I would like to ask if there is any way to insert a hexadecimal code into the generated code?

**Comment by kawakami-k** [comment]
Please use "main" branch. We plan to overwrite "fj_master" branch with "main" branch in the near future.

You can use 'xbyak_aarch64_code_array.h:dd(uint32_t code)' to write single 32-bit data at the current code pointer.
- https://github.com/fujitsu/xbyak_aarch64/blob/main/sample/add.cpp
- https://github.com/fujitsu/xbyak_aarch64/blob/main/sample/direct_write.cpp
These two sample write same binary.

**Comment by lingweiyang** [comment]
Thank you for your answer. Does this mean that I can express it as: top_[size_++]=0xb000020;

**Comment by kawakami-k** [comment]
Yes, it does.
Please be careful not to overflow the code size.
The initial code size can be given in the constructor.

```C++
#include "xbyak_aarch64.h"
using namespace Xbyak_aarch64;
class Generator : public CodeGenerator {
public:
  Generator(size_t maxSize=DEFAULT_MAX_CODE_SIZE) : CodeGenerator(maxSize) {
    top_[size_++] = 0xb000020; // machine code of "add w0, w1, w0"                                                                                                                                                                                                                                             
    ret();
  }
};
int main() {
  Generator gen(65536);
  gen.ready();
  auto f = gen.getCode<int (*)(int, int)>();
  std::cout << f(3, 4) << std::endl;
  return 0;
}
```

**Comment by lingweiyang** [comment]
How to pass runtime parameters to getCode?

**Comment by kawakami-k** [comment]
```C++
auto f = gen.getCode<int (*)(int, int)>();
```
means the function pointer `f` is defined like
```C++
int f(int, int);
```
, you can freely pass parameters like the example below.

```C++
#include "xbyak_aarch64.h"
using namespace Xbyak_aarch64;
class Generator : public CodeGenerator {
public:
  Generator(size_t maxSize=DEFAULT_MAX_CODE_SIZE) : CodeGenerator(maxSize) {
    add(w0, w1, w0);
    ret();
  }
};
int main() {
  int a = 3;
  int b = 4;
  Generator gen(65536);
  gen.ready();
  auto f = gen.getCode<int (*)(int, int)>();
  std::cout << f(a, b) << std::endl;
  return 0;
}
```

Please refer "Procedure Call Standard for the ARM 64-bit Architecture"
https://developer.arm.com/documentation/ihi0055/b/
If the number of parameters passed to JIT-ed code is less than equal to 8, they are passed through x0 - x7.
In the example above, 3 and 4 is stored in x0(w0) and x1(w1) registers, respectively.
Usually the return value is passed to caller by x0(w0) register.

As described in "Procedure Call Standard for the ARM 64-bit Architecture", 
if you use x19..x28 in your JIT-ed code, you have to store x19..x28 registgers to the stack at the beginning of your JIT-ed code, and restore them from the stack at the end of your JIT-ed code.

You may find the code below helpful.
https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/aarch64/jit_generator.hpp#L121
https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/aarch64/jit_uni_reorder.cpp#L1149

**Comment by lingweiyang** [comment]
I'm sorry, I may not be able to express the problem clearly. In fact, what I want to express is how to pass parameters in the code generation phase. For example, I want to pass in parameters M and N during code generation.

**Comment by kawakami-k** [comment]
I see. Is the sample below usefull?

```C++
#include <string>
#include "xbyak_aarch64.h"
using namespace Xbyak_aarch64;
class Generator : public CodeGenerator {
public:
  Generator() {
  }

  void generate(int m, int n) {
    int	i=0;

    for(i=0; i<m; i++) {
      add(w0, w0, n);
    }
  }

  void preamble() {}
  void postamble() {
    ret();
  }
};
int main(int argc, char *argv[]) {
  (void) argc; // -Wunused-parameter                                                                                                                                                                                                                                                                           
  Generator gen;
  gen.ready();
  gen.generate(atoi(argv[1]), atoi(argv[2]));
  gen.postamble();

  auto f = gen.getCode<int (*)(int, int)>();
  std::cout << f(atoi(argv[1]), atoi(argv[2])) << std::endl;
  return 0;
}
```

**Comment by lingweiyang** [comment]
I tried to write a simple JIT program. A segment error has occurred. If you have time, can I help you? thank you.

#include<stdio.h>
#include<cstddef>
#include <stdlib.h>
#include <stdint.h>


#define code_size 4096     

inline uint32_t *AlignedMalloc(size_t size, size_t alignment) 
{
  void *p;
  int ret = posix_memalign(&p, alignment, size);
  return reinterpret_cast<uint32_t *>( (ret == 0) ? p : 0);
}

class CodeGenerator
{
public:
      size_t maxSize_; // max size of code size (per uint32_t)
      uint32_t *top_;
      size_t size_; // code size

      CodeGenerator()
  	  {

    		maxSize_ = code_size;
    		top_=AlignedMalloc(maxSize_, 4096);
        size_ = 0;
        top_[size_++] = 0xb000020;
        top_[size_++] = 0xD65F03C0; 
  	  }

    template <class F> const F getCode() const 
      { 
        return reinterpret_cast<F>(top_); 
      }


     void ready() 
  {
   
    __builtin___clear_cache((char *)(&top_[0]), (char *)(&top_[size_])); 
  }

    void dump() const 
    {
      for (size_t i = 0; i < size_; ++i) 
      {
        printf("%08X\n", top_[i]);
      }
    }

    ~CodeGenerator() 
    {
      free(top_);
    
    }

};


int main()
{
	CodeGenerator gen;
  gen.ready();
  auto f = gen.getCode<int (*)(int, int)>();
  gen.dump();

  int c = f(3,4);
  printf("c = %d\n", c);
	return 0;
}

**Comment by kawakami-k** [comment]
It seems your sample code does not set execution privilege to the memory allocated for JIT.

**Comment by lingweiyang** [comment]
Thank you. How to solve this problem?

**Comment by kawakami-k** [comment]
Please refer xbyak_aarch64 implementation :-)
