### ISSUE TITLE
application get isa info under el0 mode

### ISSUE THREAD

**Issue by jitMatrix** [fujitsu/xbyak_aarch64#57]
Hi, i encounter `illegal instruction`  when using xbyak on Cortex-A57. It's mainly due to line https://github.com/fujitsu/xbyak_aarch64/blob/main/xbyak_aarch64/xbyak_aarch64_util.h#L68 for getting the isa info since the appliaction is running under el0 mode which has no privilege to read register. How can I get a walk around?

**Comment by nSircombe** [comment]
Hi @jitMatrix,

A similar issue was recently reported against oneDNN (see https://github.com/oneapi-src/oneDNN/issues/1025).
A quick fix would be to manually set the HW features in the src. A more permanent solution might be to use `getauxval(AT_HWCAP)`, as discussed on the oneDNN ticket.

**Comment by jitMatrix** [comment]
Thanks. It looks good:)

**Comment by kawakami-k** [comment]
Hi, @jitMatrix 
Thank you for the bug report. I'll fix the bug. Please wait a few days.

**Comment by jitMatrix** [comment]
@kawakami-k Thx.

**Comment by kawakami-k** [comment]
@jitMatrix 

I'll fix the bug
https://github.com/fujitsu/xbyak_aarch64/pull/58
It will merge the main branch soon.

**Comment by jitMatrix** [comment]
I'll close the issue. Thanks for the fix.
