### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by bkmgit** [fujitsu/xbyak_aarch64#70]
Will there be new releases? Will [semantic versioning](https://semver.org/lang/ja/) be used? Would like to make this available for Fedora linux, can use a git commit since the last release was quite some time ago, but if releases will be done, that will make packaging easier.

**Comment by kawakami-k** [comment]
Thank you for the comment. Currently, Xbyak_aarch64 doesn't have strict rule about its versioning. It's good idea to adopt [the semantic versioning](https://semver.org/) to Xbyak_aarch64.  I tagged the current implementation as v1.0.0.

**Comment by bkmgit** [comment]
Thanks.
