### ISSUE TITLE
[Bug] SIGILL on linux docker container

### ISSUE THREAD

**Issue by kawakami-k** [fujitsu/xbyak_aarch64#94]
https://github.com/fujitsu/xbyak_aarch64/pull/93#pullrequestreview-1678766855

Because linux docker container has no 
/sys/devices/system/cpu/cpu0/regs/identification/midr_el1
file, capability detection fails.

**Comment by ilya-lavrenov** [comment]
I used Apple M2 macOS14 with ubuntu **20.04** docker image.

**Comment by kawakami-k** [comment]
At this time, it may be difficult to get CPU capability correctly if the host OS and container OS are different. I wish I could find a similar example in other libraries which deals this issue.

**Comment by malfet** [comment]
Might be fixed by https://github.com/fujitsu/xbyak_aarch64/pull/96

**Comment by ilya-lavrenov** [comment]
Yes, it fixes the issue
Thanks @malfet and @kawakami-k
